# Generated by Django 5.2 on 2025-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_famousperson"),
    ]

    operations = [
        migrations.AddField(
            model_name="famousperson",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
    ]
