# Generated by Django 5.2 on 2025-05-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_famousperson_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="famousperson",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
