# Generated by Django 5.2 on 2025-05-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_alter_famousperson_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="famousperson",
            name="skin_color",
            field=models.CharField(
                choices=[("white", "White"), ("black", "Black"), ("asian", "Asian")],
                default="white",
                max_length=10,
            ),
        ),
    ]
