# Generated by Django 5.2 on 2025-05-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_famousperson_skin_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="famousperson",
            name="skin_color",
            field=models.CharField(
                choices=[
                    ("white", "White"),
                    ("black", "Black"),
                    ("asian", "Asian"),
                    ("brown", "Brown"),
                ],
                default="white",
                max_length=10,
            ),
        ),
    ]
