# Generated by Django 5.2 on 2025-05-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_alter_famousperson_skin_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="best_score_easy",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="best_score_hard",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="best_score_medium",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="famousperson",
            name="image",
            field=models.ImageField(upload_to="famous_people/"),
        ),
        migrations.AlterField(
            model_name="famousperson",
            name="skin_color",
            field=models.CharField(
                choices=[
                    ("white", "White"),
                    ("black", "Black"),
                    ("asian", "Asian"),
                    ("brown", "Brown"),
                ],
                default="white",
                max_length=20,
            ),
        ),
    ]
